### ISSUE TITLE
[Request] Spanish translation

### ISSUE THREAD

**Issue by jpturcotte** [opentoonz/opentoonz.github.io#21]
@Orphanlast just tweeted a very interesting look at YouTube trends for animation software: https://twitter.com/AugustineGraphx/status/925588136716931072 (you can also check general Google search trends, which I posted in reply). One fact that caught my attention is the number of queries from Spanish-speaking countries. In light of this, I believe it would be great to translate the homepage to Spanish. Maybe @gab3d could be interested? Thank you!

**Comment by gab3d** [comment]
I don't have any problem in translating the website into Spanish, that would take me one or two days at most, so there is no problem at all in that front.
Let me know if you want me to.

**Comment by Orphanlast** [comment]
Wow. I didn't think my post would get that much attention. Cool

**Comment by jpturcotte** [comment]
Thank you very much, @gab3d! We should ask @shun-iwasawa if he is open to that. Also, Iwasawa-san, could you look at my PR for the English translation when you have some time, please?

**Comment by shun-iwasawa** [comment]
@gab3d 
Thank you for kind proposal for Spanish translation! We'll be willing to add it.
Just one point I would like to beg you is to make sure to include the following sentence in the Spanish version of "Terms of Use" , just like the same way as [English version](https://opentoonz.github.io/e/download/opentoonz.html);

> *The Terms shall be stipulated in Japanese, and this Spanish translation is provided just for reference.

Because it is difficult for us (Dwango) to verify the translated terms precisely.

**Comment by gab3d** [comment]
@shun-iwasawa
great I'll do it, and include that regarding Terms of Use, of course.

**Comment by gab3d** [comment]
@shun-iwasawa, where can I find the web page code to translate it, and how do you want me to deliver it to you?

**Comment by shun-iwasawa** [comment]
For now there are three pages in the web site as follows;

- [opentoonz.github.io/e/index.html](https://github.com/opentoonz/opentoonz.github.io/blob/master/e/index.html) ([Raw file](https://raw.githubusercontent.com/opentoonz/opentoonz.github.io/master/e/index.html))

- [opentoonz.github.io/e/download/gts.html](https://github.com/opentoonz/opentoonz.github.io/blob/master/e/download/gts.html) ([Raw file](https://raw.githubusercontent.com/opentoonz/opentoonz.github.io/master/e/download/gts.html))

- [opentoonz.github.io/e/download/opentoonz.html](https://github.com/opentoonz/opentoonz.github.io/blob/master/e/download/opentoonz.html) ([Raw file](https://raw.githubusercontent.com/opentoonz/opentoonz.github.io/master/e/download/opentoonz.html))

You can push a PR (just like OpenToonz' main repository) including your translated html files put in some folder (say, `opentoonz.github.io/es/` ).
OR, you can download the raw html files from the links above, translate them and upload the zipped files in this thread would be also fine. Thanks!

**Comment by gab3d** [comment]
@shun-iwasawa 
Here's the Spanish translation of the web site.
[web_es.zip](https://github.com/opentoonz/opentoonz.github.io/files/1500427/web_es.zip)
Hope it's all right.

**Comment by shun-iwasawa** [comment]
Thank you @gab3d !
As I'm now working on preparing the next version, I'll check your translation and add Spanish page after releasing of it. Thank you for your patience.

**Comment by gab3d** [comment]
@shun-iwasawa 
yeah, that's fine! 
thank you :)

**Comment by gab3d** [comment]
@shun-iwasawa 
please, when you have some time, there is this website Spanish translation to be uploaded.
Thanks! :)

**Comment by shun-iwasawa** [comment]
@gab3d Thank you for your patience, finally I posted the Spanish page PR based on your translation.

**Comment by gab3d** [comment]
great! :)

**Comment by gab3d** [comment]
could it be possible for the website to check for the user's browser preferred languages and automatically display the site in the proper language (if not found, then English)?
it'd be a nice touch.
thx!

**Comment by jpturcotte** [comment]
@gab3d I have just checked, and it is not simple. However, I agree it would be great to have.

EDIT: I might have it working with PHP. @shun-iwasawa Should I open a PR?
